# Generated by Django 4.1.7 on 2023-02-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0002_todo_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=models.TextField(max_length=500),
        ),
    ]
