# Generated by Django 4.1.7 on 2023-02-26 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0005_todo_category_todo_desrcription_todo_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='category',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='desrcription',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='priority',
        ),
    ]
