# Generated by Django 4.1.7 on 2023-02-26 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0007_todo_category_todo_desrcription_todo_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='desrcription',
            new_name='description',
        ),
    ]
