# Generated by Django 4.1.7 on 2023-02-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0008_rename_desrcription_todo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='development_state',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
