# Generated by Django 4.1.7 on 2023-02-27 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0009_todo_development_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(default=datetime.date(2023, 2, 27)),
        ),
    ]
