# Generated by Django 4.1.7 on 2023-02-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0010_alter_todo_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
