# Generated by Django 4.1.7 on 2023-02-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0011_alter_todo_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='expire_date',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
